#!/usr/bin/env bash
# if ufw is not installed
sudo apt install ufw

#block all incoming traffic
sudo ufw default deny incoming

#allow all outgoing traffic
sudo ufw default allow outgoing

#allow traffic through these TCP ports
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

#enable ufw
sudo ufw enable

#Redirect traffic from port 8080 to 80
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
